theme: jekyll-theme-cayman
show_downloads: true
title: SimplyTranslator
description: SimplyTranslator is a Firefox Extensions to Traslate web site
github :
   zip_url : http://example.com/download.zip 
