theme: jekyll-theme-cayman
show_downloads: true
title: SimplyTranslator
description: Cayman is a clean, responsive theme for GitHub Pages.
SimplyTranslator is a Firefox Extensions to Traslate web site
